name: Eggnine.TrashTaf_branch 

on: 
  push: 
    branches: [ "*", "!main" ] 

jobs: 
  stub: 
    uses: rf-eggnine/TrashTaf/.github/reusable/build-and-test.yml
    with: 
      operatingSystem: ubuntu-24.04 
      browser: firefox  
    secrets: inherit 