name: Eggnine.TrashTaf_branch 

on: 
  push: 
    branches: [ "*", "!main" ] 

jobs: 
  branch: 
    uses: rf-eggnine/TrashTaf/.github/workflows/reuse-build-and-test.yml@28-integrates-with-postgresql-for-recording-test-results 
    with: 
      operating-system: ubuntu-24.04 
      browser: firefox  
    secrets: inherit 
