name: Eggnine.TrashTaf_branch 

on: 
  push: 
    branches: [ "*", "!main" ] 

jobs: 
  branch: 
    uses: rf-eggnine/TrashTaf/.github/workflows/reuse-build-and-test.yml@main 
    with: 
      operating-system: ubuntu-latest
      browser: chrome  
    secrets: inherit 
