name: Eggnine.TrashTas_branch 

on: 
  push: 
    branches: [ "*", "!main" ] 

jobs: 
  branch: 
    uses: rf-eggnine/TrashTas/.github/workflows/reuse-build-and-test.yml@main 
    with: 
      operating-system: ubuntu-latest
      browser: chrome 
      browser-version: '127' 
    secrets: inherit 
