name: Eggnine.TrashTaf_main 

on: 
  push: 
    branches: [ "main" ] 
  pull_request: 
    branches: [ "main" ] 
    
jobs: 
  main: 
    uses: rf-eggnine/TrashTaf/.github/workflows/reuse-build-and-test.yml@28-integrates-with-postgresql-for-recording-test-results 
    with: 
      operating-system: ${{ matrix.operatingSystem }} 
      browser: firefox 
    secrets: inherit 

    strategy: 
      fail-fast: false 
      matrix: 
        operatingSystem: [ ubuntu-22.04, windows-2022, macos-13] 
