name: Eggnine.TrashTaf_main 

on: 
  push: 
    branches: [ "main" ] 
  pull_request: 
    branches: [ "main" ] 
    
jobs: 
  main: 
    uses: rf-eggnine/TrashTaf/.github/workflows/reuse-build-and-test.yml@main 
    with: 
      operating-system: ${{ matrix.operatingSystem }} 
      browser: firefox 
    secrets: inherit 

    strategy: 
      fail-fast: false 
      matrix: 
        operatingSystem: [ ubuntu-latest, windows-latest, macos-latest] 
