name: Eggnine.TrashTaf_monthly_chrome

on:
  workflow_dispatch: 
  schedule:
  - cron: 0 18 1 */1 *      

jobs: 
  main: 
    uses: rf-eggnine/TrashTaf/.github/workflows/reuse-build-and-test.yml@main 
    with: 
      operating-system: ${{ matrix.operatingSystem }} 
      browser: chrome 
    secrets: inherit 

    strategy: 
      fail-fast: false 
      matrix: 
        operatingSystem: [ ubuntu-22.04, ubuntu-24.04, windows-2019, windows-2022, macos-12, macos-13] 
        
